name: Discord Notify

on:
  pull_request_target:
<<<<<<< HEAD
    types: [ labeled ]

jobs:
  notify:
    if: ${{ github.event.label.name == 'React Core Team' }}
=======
    types: [opened, ready_for_review]

permissions: {}

jobs:
  check_maintainer:
    uses: facebook/react/.github/workflows/shared_check_maintainer.yml@main
    permissions:
      # Used by check_maintainer
      contents: read
    with:
      actor: ${{ github.event.pull_request.user.login }}

  notify:
    if: ${{ needs.check_maintainer.outputs.is_core_team == 'true' }}
    needs: check_maintainer
>>>>>>> e07ac94bc2c1ffd817b13930977be93325e5bea9
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embed-author-name: ${{ github.event.pull_request.user.login }}
          embed-author-url: ${{ github.event.pull_request.user.html_url }}
          embed-author-icon-url: ${{ github.event.pull_request.user.avatar_url }}
          embed-title: '#${{ github.event.number }} (+${{github.event.pull_request.additions}} -${{github.event.pull_request.deletions}}): ${{ github.event.pull_request.title }}'
          embed-description: ${{ github.event.pull_request.body }}
<<<<<<< HEAD
          embed-url: ${{ github.event.pull_request.html_url }}
=======
          embed-url: ${{ github.event.pull_request.html_url }}
>>>>>>> e07ac94bc2c1ffd817b13930977be93325e5bea9
